### ISSUE TITLE
authors_refine() 

### ISSUE THREAD

**Issue by aurielfournier** [embruna/refnet#46]
when `authors_clean()` does too good a job and as a result list$authors is empty, then `authors_refine()` errors out.

Can we please add something to authors_refine() to address this so it does not throw an error?

**Comment by birderboone** [comment]
done

**Comment by aurielfournier** [comment]
```r
> eb_refined <- authors_refine(authors=eb_authors$authors, master=eb_authors$master)
no non-missing arguments to min; returning Inf
```

I'm still getting errors when I run `authors_refine()` on the eb dataset.

**Comment by birderboone** [comment]
That would be because I forgot to push last night because I had a different copy than the repository and didnt feel like figuring out what was wrong. its uh...pushed now? So try again

**Comment by aurielfournier** [comment]
excellent. 

Thank you!
